### ISSUE TITLE
Placeholder still exists

### ISSUE THREAD

**Issue by KirkEasterson** [david-morris/SlideImages#1]
Will the dataset be uploaded soon? I am very interested in using it.

**Comment by david-morris** [comment]
Sorry for the delay.  We're now preparing and reviewing the dataset.  I expect to have it uploaded by the end of the year.

**Comment by david-morris** [comment]
The dataset is now available [here](https://data.uni-hannover.de/dataset/slideimages).  I'll close the issue while working on getting the code shared, since the question here was specifically about the dataset.
